Iter15
MlDenis/prometheus_wannabe pull request #32
Opened 2023-07-31 13:22 UTC by MlDenis

2023-08-01 08:59 UTC, rktkov requested changes

2023-08-01 08:59 UTC, rktkov commented on internal/test/helpers.go
> +package test
В пакете нет тестов. Кода который может быть запущен с помощью go test. Поэтому пакет надо переименовать, чтобы он говорил о том, какие задачи решает код внутри него.

2023-08-01 08:59 UTC, rktkov commented on internal/metrics/types/counterMetric.go
> +func (m *counterMetric) JumpToTheOriginalState() {
ResetState - короче и суть отражает.

2023-08-01 08:59 UTC, rktkov commented on internal/metrics/types/gaugeMetric.go
> +	lock  sync.RWMutex
В метрике точно не нужен мютекс, природа ее использования должна быть прямолинейна и однозначна - один раз прочитать и дальше только считывать значения в нужные момент. А когда произойдет отправка данных экземпляр структуры должен считать использованным и данные из него не нужными.

2023-08-01 08:59 UTC, rktkov commented on cmd/server/main.go
> +	"compress/gzip"
Импорты должны быть сгруппированы в 3 блока (в порядке размещения)
- пакеты из стандартной библиотеки
- внешние пакеты
- внутренние пакеты
чтобы форматтер кода не смешивал пакеты опять сортируя их по алфавиту каждый блок надо отделить друг от друга пустой строкой.
Этот комментарий надо применить ко всем импортам в проекте!

2023-08-01 08:59 UTC, rktkov commented on internal/metrics/sendler/http/httpMetricsSendler.go
> +	"github.com/sirupsen/logrus"
Есть отдельный внутренний пакет logger  внутри которого скрыто использование внешнего пакета - почему тут используется внешний пакет? Везде надо использовать внутренний пакет для логгирования.

2023-08-01 08:59 UTC, rktkov commented on internal/metrics/sendler/http/httpMetricsSendler.go
> +	parallelLimit    int
почему бы не сделать metricaPusherConfig полем, и не копировать значения в момент инициализации.

2023-08-01 08:59 UTC, rktkov commented on internal/metrics/provider/runtime/runtimeMetricsProvider.go
> +	metrics []metrics.Metric
Я бы метрики не сохранял. А каждый раз отправлял то, что вернулось из стата. И тогда не надо было бы мютекс вешать.

2023-08-01 08:59 UTC, rktkov commented on internal/metrics/metricsProvider.go
> +type MetricsProvider interface {
Я бы сделал только метод GetMetrics без апдейта и не хранил бы состояния между 2-мя вызовами в провайдере.

2023-10-27 05:34 UTC, YudinAndrey reviewed
Привет!
Оставил несколько комментариев, и еще не нашел работу с retry

2023-10-27 05:34 UTC, YudinAndrey commented on cmd/agent/main.go
> +	"github.com/MlDenis/prometheus_wannabe/internal/hash"
Давай на будущее линтер подключим? 
https://golangci-lint.run/ с дефолтными настройками будет более чем

2023-10-27 05:34 UTC, YudinAndrey commented on cmd/agent/main.go
> +func createConfig() (*config, error) {
Актуальный комментарий, давай поправим, так как это последний спринт по доработкам этого проекта

2023-10-27 05:34 UTC, YudinAndrey commented on cmd/server/main.go
> +type config struct {
работу с конфигом нужно вынести в отдельный пакет

2023-10-27 05:34 UTC, YudinAndrey commented on cmd/server/main.go
> +type config struct {
или хотя бы файлик рядом c main, например config.go

2023-10-27 05:34 UTC, YudinAndrey commented on internal/database/postgre/initializer.go
> +package postgre
Вот это выглядит немного страшно, давай переделаем на миграцию на основе goose?

2023-10-27 05:34 UTC, YudinAndrey commented on internal/database/postgre/initializer.go
> +package postgre
И от процедур тоже хотелось бы отказаться в пользу запросов в методах

2023-10-27 05:34 UTC, YudinAndrey commented on internal/database/stub/stubDatabase.go
> +	panic("not implement")
Может вот это удалить если оно паникует?

2023-10-27 05:34 UTC, YudinAndrey commented on internal/logger/logger.go
> +	"fmt"
Не думал вот тут на более современный zap переделать?

2023-12-07 19:16 UTC, YudinAndrey reviewed
в целом все более менее окей, но давай поправим комменты, которые я написал и критические из тех, что оставил предыдущий ревьюер

2023-12-07 19:16 UTC, YudinAndrey commented on internal/metrics/types/gaugeMetric.go
> +	lock  sync.RWMutex
Мьютекс тут все еще не нужен

2023-12-07 19:16 UTC, YudinAndrey commented on internal/database/postgre/postgreDataBase.go
> +		const command = "" +
можно использовать другие кавычки и не конкатенировать строку

2023-12-07 19:16 UTC, YudinAndrey commented on internal/database/postgre/postgreDataBase.go
> +		const command = "" +
и странно что это константа, это же обычная строка

2023-12-08 14:07 UTC, YudinAndrey reviewed
Оставил еще пару комментов и нужно с сортировкой импортов разобраться во всем проекте

2023-12-08 14:07 UTC, YudinAndrey commented on internal/metrics/types/counterMetric.go
> +	m.setValue(0)
тоже актуальный комментарий был

ResetState - короче и суть отражает.

2023-12-08 14:07 UTC, YudinAndrey commented on internal/metrics/storage/storageBackup.go
> +	io.Closer
а это зачем тут?

2023-12-08 19:10 UTC, MlDenis commented on cmd/agent/main.go
> +	"github.com/MlDenis/prometheus_wannabe/internal/logger"
> А он работает? есть ощущение, что линтер на экшнах не прогоняется

Я его ручками запускаю

2024-02-01 08:44 UTC, merged